apiVersion: apps/v1
kind: Deployment
metadata:
  name: vul-dep 
spec:
  selector:
    matchLabels:
      app: flask 
  replicas: 1 # change the replica 
  template:
    metadata:
      labels:
        app: flask
    spec:
      serviceAccountName: secret-access
      containers:
      - name: vul-app
        image: <update-the-image-name> # change the image name 
        ports:
        - containerPort: 5000
